import { getTokenThemeVal } from '@kyndryl-design-system/shidoka-foundation/common/helpers/color';

export const getColorPalette = (key) => {
  const palettes = {
    // categorical: [
    //   '#64b5e1',
    //   '#81E1B5',
    //   '#FF850A',
    //   '#F3ACD6',
    //   '#BD93E5',
    //   '#95D3F0',
    //   '#49C588',
    //   '#FFBC48',
    //   '#F378B1',
    //   '#D5B5F6',
    // ],
    categorical: [
      getTokenThemeVal('--kd-color-data-viz-categorical-01-01'),
      getTokenThemeVal('--kd-color-data-viz-categorical-01-02'),
      getTokenThemeVal('--kd-color-data-viz-categorical-01-03'),
      getTokenThemeVal('--kd-color-data-viz-categorical-01-04'),
      getTokenThemeVal('--kd-color-data-viz-categorical-01-05'),
      getTokenThemeVal('--kd-color-data-viz-categorical-01-06'),
      getTokenThemeVal('--kd-color-data-viz-categorical-01-07'),
      getTokenThemeVal('--kd-color-data-viz-categorical-01-08'),
      getTokenThemeVal('--kd-color-data-viz-categorical-01-09'),
      getTokenThemeVal('--kd-color-data-viz-categorical-01-010'),
    ],
    // sequential01: [
    //   '#ACE1F8',
    //   '#95D3F0',
    //   '#7EC4E9',
    //   '#64B5E1',
    //   '#48A5DA',
    //   '#3A94C6',
    //   '#3082AF',
    //   '#236F96',
    //   '#155B7F',
    //   '#004765',
    // ],
    sequential01: [
      getTokenThemeVal('--kd-color-data-viz-sequential-01-10'),
      getTokenThemeVal('--kd-color-data-viz-sequential-01-20'),
      getTokenThemeVal('--kd-color-data-viz-sequential-01-30'),
      getTokenThemeVal('--kd-color-data-viz-sequential-01-40'),
      getTokenThemeVal('--kd-color-data-viz-sequential-01-50'),
      getTokenThemeVal('--kd-color-data-viz-sequential-01-60'),
      getTokenThemeVal('--kd-color-data-viz-sequential-01-70'),
      getTokenThemeVal('--kd-color-data-viz-sequential-01-80'),
      getTokenThemeVal('--kd-color-data-viz-sequential-01-90'),
      getTokenThemeVal('--kd-color-data-viz-sequential-01-100'),
    ],
    // sequential02: [
    //   '#9BEECA',
    //   '#81E1B5',
    //   '#66D39F',
    //   '#49C588',
    //   '#25B574',
    //   '#00A275',
    //   '#008D72',
    //   '#00776B',
    //   '#00615F',
    //   '#004A4F',
    // ],
    sequential02: [
      getTokenThemeVal('--kd-color-data-viz-sequential-02-10'),
      getTokenThemeVal('--kd-color-data-viz-sequential-02-20'),
      getTokenThemeVal('--kd-color-data-viz-sequential-02-30'),
      getTokenThemeVal('--kd-color-data-viz-sequential-02-40'),
      getTokenThemeVal('--kd-color-data-viz-sequential-02-50'),
      getTokenThemeVal('--kd-color-data-viz-sequential-02-60'),
      getTokenThemeVal('--kd-color-data-viz-sequential-02-70'),
      getTokenThemeVal('--kd-color-data-viz-sequential-02-80'),
      getTokenThemeVal('--kd-color-data-viz-sequential-02-90'),
      getTokenThemeVal('--kd-color-data-viz-sequential-02-100'),
    ],
    // sequential03: [
    //   '#FFD46A',
    //   '#FFBC48',
    //   '#FFA329',
    //   '#FF850A',
    //   '#F26E01',
    //   '#D86301',
    //   '#BC5802',
    //   '#9E4D02',
    //   '#813F01',
    //   '#643000',
    // ],
    sequential03: [
      getTokenThemeVal('--kd-color-data-viz-sequential-03-10'),
      getTokenThemeVal('--kd-color-data-viz-sequential-03-20'),
      getTokenThemeVal('--kd-color-data-viz-sequential-03-30'),
      getTokenThemeVal('--kd-color-data-viz-sequential-03-40'),
      getTokenThemeVal('--kd-color-data-viz-sequential-03-50'),
      getTokenThemeVal('--kd-color-data-viz-sequential-03-60'),
      getTokenThemeVal('--kd-color-data-viz-sequential-03-70'),
      getTokenThemeVal('--kd-color-data-viz-sequential-03-80'),
      getTokenThemeVal('--kd-color-data-viz-sequential-03-90'),
      getTokenThemeVal('--kd-color-data-viz-sequential-03-100'),
    ],
    // sequential04: [
    //   '#F2C4E2',
    //   '#F3ACD6',
    //   '#F493C5',
    //   '#F378B1',
    //   '#EE5D97',
    //   '#DC4B89',
    //   '#C4407E',
    //   '#AB3272',
    //   '#922365',
    //   '#781256',
    // ],
    sequential04: [
      getTokenThemeVal('--kd-color-data-viz-sequential-04-10'),
      getTokenThemeVal('--kd-color-data-viz-sequential-04-20'),
      getTokenThemeVal('--kd-color-data-viz-sequential-04-30'),
      getTokenThemeVal('--kd-color-data-viz-sequential-04-40'),
      getTokenThemeVal('--kd-color-data-viz-sequential-04-50'),
      getTokenThemeVal('--kd-color-data-viz-sequential-04-60'),
      getTokenThemeVal('--kd-color-data-viz-sequential-04-70'),
      getTokenThemeVal('--kd-color-data-viz-sequential-04-80'),
      getTokenThemeVal('--kd-color-data-viz-sequential-04-90'),
      getTokenThemeVal('--kd-color-data-viz-sequential-04-100'),
    ],
    // sequential05: [
    //   '#E2C6FF',
    //   '#D5B5F6',
    //   '#C9A5ED',
    //   '#BD93E5',
    //   '#B181DB',
    //   '#A36FD0',
    //   '#945CC2',
    //   '#8548B4',
    //   '#7431A4',
    //   '#641195',
    // ],
    sequential05: [
      getTokenThemeVal('--kd-color-data-viz-sequential-05-10'),
      getTokenThemeVal('--kd-color-data-viz-sequential-05-20'),
      getTokenThemeVal('--kd-color-data-viz-sequential-05-30'),
      getTokenThemeVal('--kd-color-data-viz-sequential-05-40'),
      getTokenThemeVal('--kd-color-data-viz-sequential-05-50'),
      getTokenThemeVal('--kd-color-data-viz-sequential-05-60'),
      getTokenThemeVal('--kd-color-data-viz-sequential-05-70'),
      getTokenThemeVal('--kd-color-data-viz-sequential-05-80'),
      getTokenThemeVal('--kd-color-data-viz-sequential-05-90'),
      getTokenThemeVal('--kd-color-data-viz-sequential-05-100'),
    ],
    // divergent01: [
    //   '#004765',
    //   '#155B7F',
    //   '#236F96',
    //   '#3082AF',
    //   '#3A94C6',
    //   '#48A5DA',
    //   '#64B5E1',
    //   '#7EC4E9',
    //   '#95D3F0',
    //   '#ACE1F8',
    //   '#DEFFEF',
    //   '#FFD46A',
    //   '#FFBC48',
    //   '#FFA329',
    //   '#FF850A',
    //   '#F26E01',
    //   '#D86301',
    //   '#BC5802',
    //   '#9E4D02',
    //   '#813F01',
    //   '#643000',
    // ],
    divergent01: [
      getTokenThemeVal('--kd-color-data-viz-divergent-01-negative-100'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-negative-90'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-negative-80'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-negative-70'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-negative-60'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-negative-50'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-negative-40'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-negative-30'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-negative-20'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-negative-10'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-div-neu'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-positive-10'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-positive-20'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-positive-30'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-positive-40'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-positive-50'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-positive-60'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-positive-70'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-positive-80'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-positive-90'),
      getTokenThemeVal('--kd-color-data-viz-divergent-01-positive-100'),
    ],
    // divergent02: [
    //   '#004A4F',
    //   '#00615F',
    //   '#00776B',
    //   '#008D72',
    //   '#00A275',
    //   '#25B574',
    //   '#49C588',
    //   '#66D39F',
    //   '#81E1B5',
    //   '#9BEECA',
    //   '#EBF8FE',
    //   '#F2C4E2',
    //   '#F3ACD6',
    //   '#F493C5',
    //   '#F378B1',
    //   '#EE5D97',
    //   '#DC4B89',
    //   '#C4407E',
    //   '#AB3272',
    //   '#922365',
    //   '#781256',
    // ],
    divergent02: [
      getTokenThemeVal('--kd-color-data-viz-divergent-02-negative-100'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-negative-90'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-negative-80'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-negative-70'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-negative-60'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-negative-50'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-negative-40'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-negative-30'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-negative-20'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-negative-10'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-div-neu'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-positive-10'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-positive-20'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-positive-30'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-positive-40'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-positive-50'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-positive-60'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-positive-70'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-positive-80'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-positive-90'),
      getTokenThemeVal('--kd-color-data-viz-divergent-02-positive-100'),
    ],
    rag03: ['#1FA452', '#F5C400', '#CC1800'],
    rag08: [
      '#1FA452',
      '#E5F7EB',
      '#FEF9E5',
      '#F5C400',
      '#F7E6E6',
      '#CC1800',
      '#E9F2FF',
      '#1473FF',
    ],
  };

  return palettes[key];
};
